### PR TITLE
nice UX when importing conu

### LINKED ISSUE #35: let users easily import conu
`import conu` should be just enough, no need to dig deep into the hierarchy

we also need to test this

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #35

the other commit:
```
remove complex pgsql example

we will provide a new, up-to-date example in future; let's remove the
present one for now so it doesn't clutter the repository
```

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/QlGu](https://da.gd/QlGu)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/hhCS](https://da.gd/hhCS)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/4LlRM](https://da.gd/4LlRM)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
updated

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Qsntl](https://da.gd/Qsntl)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/DT9L](https://da.gd/DT9L)__
* Comment: __See details for logs__

**Pull request merged**
