### PR TITLE
separate tests

### PR DESCRIPTION
**Pull request by TomasTomecek**
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by bkabrda** [comment]
Could we have py.test, pretty please? Nothing personal against nose, I just find py.test much more convenient and like it's advanced capabilities like `pytest.mark.parametrize`.

**Comment by TomasTomecek** [comment]
Honestly? I even dislike nose: I had a bug in my test and I had to `^C` the run and nose just said: `ok`, and when I rerun with pytest, it showed traceback so I knew where the execution was stuck.

Can do!

**Comment by TomasTomecek** [comment]
done, waiting for CI

**Comment by bkabrda** [comment]
LGTM, but travis is unhappy. When you fix, I'll merge this.

**Comment by TomasTomecek** [comment]
uhhh

```
  - pytest # or py.test for Python versions 3.5 and below
```

**Comment by TomasTomecek** [comment]
finally green!

**Pull request merged**
