### PR TITLE
better docs for logs()

### LINKED ISSUE #88: Improve docs for conu.apidefs.container.logs method
* [ ] describe the method more thoroughly
* [ ] provide an example
* [ ] do `stream=True`, let logs return iterator always (we all agreed on this @dhodovsk @phracek and myself)

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #88

~~Blocked by https://github.com/sphinx-doc/sphinx/issues/4479.~~

TODO:
* [x] more tests
* [ ] fix examples

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Hpgmh](https://da.gd/Hpgmh)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
@dhodovsk @phracek is the docs better? should I update it even more?

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/E4dLS](https://da.gd/E4dLS)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
wow, CI passed

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/dhR7b](https://da.gd/dhR7b)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
let the rebasing begin!

**Pull request merged**
