### PR TITLE
WIP WIP nspawn madness WIP WIP

### PR DESCRIPTION
**Pull request by TomasTomecek**
Please don't look yet. Let's merge #180 first, then I rebase, then we can figure out what we want to do.

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/0KKf](https://da.gd/0KKf)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
Just rebased.

**Comment by TomasTomecek** [comment]
7 tests passed, 1 failed:
```
backend.py                 121 INFO     conu has initiated, welcome to the party!
image.py                   232 INFO     nspawn image bootstrapped is not present probably: Could not get path to image: No image 'bootstrapped' known                       

image.py                   376 INFO     run container via binary in background
container.py               425 INFO     Stating machine CONU.tajlqcsdit
container.py               431 INFO     machine: CONU.tajlqcsdit starting finished
```

**Comment by jscotka** [comment]
@TomasTomecek I think you missed last commit, because I've fixed it this issue at the end

**Pull request merged**
