### PR TITLE
s/DockerRunCommand/DockerRunBuilder/

### LINKED ISSUE #68: Rename DockerRunCommand
based on conversation in https://github.com/fedora-modularity/conu/pull/61#discussion_r152566588

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #68

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/gscpL](https://da.gd/gscpL)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
rebayz'd

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/DtUQy](https://da.gd/DtUQy)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/ZzFq4](https://da.gd/ZzFq4)__
* Comment: __See details for logs__

**Pull request merged**
