### PR TITLE
sanitize Image class

### PR DESCRIPTION
**Pull request by TomasTomecek**
I didn't like how Image performs more things than it should, e.g. pulling the image by default. I was also confused by several variable/attribute names -- I think we should be as close to docker terminology as possible (check manpages). This is probably not final. I will continue tomorrow.

@jscotka Honzo, can you take a look please?

### CODE REVIEW

**Comment by jscotka** [comment]
I'll check it tomorrow. Could you please fix testsuite in this pr. Ive added comment to https://github.com/fedora-modularity/conu/pull/6 what caused this regression to see if nothing is broken by this change

**Comment by TomasTomecek** [comment]
can't see the comment :/

**Comment by jscotka** [comment]
In utils, core. By PR6, there were changed name of parameter of function wait from function to fnc, but in methods wait_inet and wait_file, there is still remains parameter function instead of fnc.

**Comment by TomasTomecek** [comment]
@jscotka I fixed that in this PR, I'm not planning to fix the logging issue, I opened a dedicated issue for that.

What do I need to do to have this merged?

**Pull request merged**
