### PR TITLE
tests in container

### PR DESCRIPTION
**Pull request by TomasTomecek**
blocked on https://github.com/projectatomic/atomic/issues/1113

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Ol4c](https://da.gd/Ol4c)__
* Comment: __This is testing CI__

**Comment by TomasTomecek** [comment]
Will update the PR soon, I hope.

TODO:
* [ ] don't implement rw container mounts (not reliable)
* [ ] remove functionality to put stuff into container - the use case is not clear

**Comment by TomasTomecek** [comment]
Built on top of #43. So please review that one first.

**Comment by TomasTomecek** [comment]
I removed .travis.yml
I cleaned Makefile and setup.py
Tests now run in a container.

**Pull request merged**
