### PR TITLE
0.1.0 release

### PR DESCRIPTION
**Pull request by TomasTomecek**
This branch is present in upstream repo: feel free to add commits to it, or even rebase it.

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/pEZkH](https://da.gd/pEZkH)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/RDyWK](https://da.gd/RDyWK)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/mRCi](https://da.gd/mRCi)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Mtob9](https://da.gd/Mtob9)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/iSan](https://da.gd/iSan)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/wSV1](https://da.gd/wSV1)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
damn, I can't approve my own PR

**Pull request merged**
