### PR TITLE
wip - nicer Container interface

### PR DESCRIPTION
**Pull request by TomasTomecek**
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by jscotka** [comment]
Hi, travis is broken, i'll review it, after travis will be green

**Comment by TomasTomecek** [comment]
marking this as wip since I wanna work other PR first

**Comment by TomasTomecek** [comment]
waiting for #21, will rebase then

**Comment by TomasTomecek** [comment]
I'm closing, it's impossible to rebase.

**Pull request closed without merging**
