### PR TITLE
update installation instructions

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/9U4f](https://da.gd/9U4f)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
@jscotka Honzo, that's a really good point. I completely forgot about it. The problem is that CentOS has docker-py-1 while we are using docker-py-2:

```
--> Finished Dependency Resolution
Error: Package: python2-conu-0.1.0-1.el7.centos.noarch (/python2-conu-0.1.0-1.el7.centos.noarch)
           Requires: python2-six
Error: Package: python2-conu-0.1.0-1.el7.centos.noarch (/python2-conu-0.1.0-1.el7.centos.noarch)
           Requires: source-to-image
Error: Package: 1:atomic-1.20.1-9.git436cf5d.el7.centos.x86_64 (extras)
           Requires: python-docker-py >= 1.7.2-1
           Available: docker-python-1.4.0-115.el7.x86_64 (extras)
               python-docker-py = 1.4.0-115.el7
           Available: python-docker-py-1.10.6-1.el7.noarch (extras)
               python-docker-py = 1.10.6-1.el7
           Available: python-docker-py-1.10.6-3.el7.noarch (extras)
               python-docker-py = 1.10.6-3.el7
Error: Package: 1:skopeo-0.1.27-1.git93876ac.el7.x86_64 (v)
           Requires: skopeo-containers = 0.1.27-1.git93876ac.el7
           Available: 1:skopeo-containers-0.1.20-2.1.gite802625.el7.x86_64 (extras)
               skopeo-containers = 1:0.1.20-2.1.gite802625.el7
           Available: 1:skopeo-containers-0.1.23-1.git1bbd87f.el7.x86_64 (extras)
               skopeo-containers = 1:0.1.23-1.git1bbd87f.el7
           Available: 1:skopeo-containers-0.1.24-1.dev.git28d4e08.el7.x86_64 (extras)
               skopeo-containers = 1:0.1.24-1.dev.git28d4e08.el7
           Available: 1:skopeo-containers-0.1.26-2.dev.git2e8377a.el7.centos.x86_64 (extras)
               skopeo-containers = 1:0.1.26-2.dev.git2e8377a.el7.centos
           Installing: 1:skopeo-containers-0.1.27-1.git93876ac.el7.x86_64 (v)
               skopeo-containers = 1:0.1.27-1.git93876ac.el7
Error: Package: python2-conu-0.1.0-1.el7.centos.noarch (/python2-conu-0.1.0-1.el7.centos.noarch)
           Requires: python2-requests
```

https://github.com/fedora-modularity/conu/issues/106

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://paste.fedoraproject.org/paste/TpD2dkVytBQwA6VdvWi9Sg/](https://paste.fedoraproject.org/paste/TpD2dkVytBQwA6VdvWi9Sg/)__
* Comment: __See details for logs__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/dGCYK](https://da.gd/dGCYK)__
* Comment: __See details for logs__

**Pull request merged**
