### PR TITLE
WIP: do not merge - testing PR for test automation

### PR DESCRIPTION
**Pull request by jscotka**

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/yiCXb](https://da.gd/yiCXb)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/4pCn](https://da.gd/4pCn)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/QM8oW](https://da.gd/QM8oW)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/pyYAX](https://da.gd/pyYAX)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/ihgu](https://da.gd/ihgu)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/sgAW](https://da.gd/sgAW)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/01AH](https://da.gd/01AH)__
* Comment: __This is testing CI__

**Comment by TomasTomecek** [comment]
@jscotka can we close this?

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/BeJjV](https://da.gd/BeJjV)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/azLeM](https://da.gd/azLeM)__
* Comment: __This is testing CI__

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: success, return code = __0__ 
* Result url: __[https://da.gd/azLeM](https://da.gd/azLeM)__
* Comment: __This is testing CI__

**Comment by TomasTomecek** [comment]
Closing this, since CI is working now. Feel free to reopen if needed

**Pull request closed without merging**
