### PR TITLE
Add config for PyPI to see description on the PyPI web

### LINKED ISSUE #183: please add project description to pypi
It is user unfriendly that page: https://pypi.org/project/conu/
has no project descriptipon (shows text UNKNOWN). would be nice to have there some autogenerated if possible.

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
Signed-off-by: lachmanfrantisek <flachman@redhat.com>

Resolves  #183

### CODE REVIEW

**Comment by psklenar** [comment]
## jenkins/superCI comment
* Status: failure, return code = __1__ 
* Result url: __[https://da.gd/Skaq4](https://da.gd/Skaq4)__
* Comment: __See details for logs__

**Comment by TomasTomecek** [comment]
LGTM, it'll be ugly, but that's issue of pypi

**Comment by lachmanfrantisek** [comment]
> it'll be ugly, but that's issue of pypi

Yes, we can look for the automatic converting `README.md` to RST later. Thanks for the approval.

**Comment by TomasTomecek** [comment]
...or teach warehouse markdown :)

**Pull request merged**
